services:
  tallermecanico-mariadb:
    container_name: tallermecanico-mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tallerMecanico
      - MYSQL_USER=taller
      - MYSQL_PASSWORD=taller
    volumes:
      - volumen-tallermecanico:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  volumen-tallermecanico:
